server:
  port: 8080
spring:
  profiles:
    active: test
  application:
    name: tools
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/back_car?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: root
    filters: stat,wall
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 30
      test-on-borrow: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000

upload-file:
  imgPath: D:\\imgs
  imgUrl: http://127.0.0.1/img/
  imgThumbPath: E:\\thumbimgs
  imgThumbUrl: http://127.0.0.1/thumb/

alipay:
  app_cert_path: /crt/appCertPublicKey_2021001157613961.crt
  alipay_root_cert_path: /crt/alipayRootCert.crt
  alipay_cert_path: /crt/alipayCertPublicKey_RSA2.crt
